name: oh_tp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_localizations:
    sdk: flutter
  flutter_sms_inbox: ^1.0.3
  get_it: ^7.6.0
  get_it_hooks: ^2.0.1
  google_fonts: ^5.1.0
  intl: ^0.18.0
  mobile_scanner: ^3.3.0
  permission_handler: ^10.4.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
