// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJz0w8D937mVSjAAyjYXvFlmRbr_Ax5Ow',
    appId: '1:165333625696:web:249756c7d7200430c9cc05',
    messagingSenderId: '165333625696',
    projectId: 'oh-tp-1631b',
    authDomain: 'oh-tp-1631b.firebaseapp.com',
    databaseURL: 'https://oh-tp-1631b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oh-tp-1631b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkUErdFNKEa53NFh5Yb3esoD_ot5eQzc',
    appId: '1:165333625696:android:8c0a94114e2933bfc9cc05',
    messagingSenderId: '165333625696',
    projectId: 'oh-tp-1631b',
    databaseURL: 'https://oh-tp-1631b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oh-tp-1631b.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbvM_9F7eg9uTWAbo4kpcLTD56RNANZDM',
    appId: '1:165333625696:ios:98047942a9b8e637c9cc05',
    messagingSenderId: '165333625696',
    projectId: 'oh-tp-1631b',
    databaseURL: 'https://oh-tp-1631b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'oh-tp-1631b.appspot.com',
    iosClientId: '165333625696-p1dg54dsv0bqn9uuvo51rh5bh4k2jvnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.ohTp.RunnerTests',
  );
}
